sudo: required
language: java
install: skip

os: linux
dist: focal

services:
  - docker

before_install:
  - pip install awscli
  - export PATH=$PATH:$HOME/.local/bin

#env:
#  global:
#    - secure: DOCKER_PASSWORD
#    - secure: DOCKER_USERNAME

script:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - chmod +x $TRAVIS_BUILD_DIR/install-jdk.sh
  - export JAVA_HOME=$HOME/openjdk17
  - $TRAVIS_BUILD_DIR/install-jdk.sh -F 17 --target $JAVA_HOME
  - rm install-jdk.sh
  - rm jdk.tar.gz
  - chmod +x gradlew
  - ./gradlew assemble
  - cd server
  - sudo docker build -t tictactoe .

deploy:
  - provider: heroku
    run:
      - docker login --username=_ --password=$(heroku auth:token) registry.heroku.com
      - docker tag tictactoe registry.heroku.com/grifisaa-tictactoe/web
      - docker push registry.heroku.com/grifisaa-tictactoe/web
      - heroku container:release web
    on:
      branch: develop
#  - provider: script
#    script: bash aws_docker_push.sh
#    on:
#      branch: develop