language: java
install: skip

os: linux
dist: focal

services:
  - docker

script:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - chmod +x $TRAVIS_BUILD_DIR/install-jdk.sh
  - export JAVA_HOME=$HOME/openjdk17
  - $TRAVIS_BUILD_DIR/install-jdk.sh -F 17 --target $JAVA_HOME
  - chmod +x gradlew
  - ./gradlew assemble
  - cd server
  - sudo docker build -t grifisaa/ttt:1.0 .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push grifisaa/ttt:1.0

