sudo: required
language: java
install: skip

os: linux
dist: focal

services:
  - docker

env:
  global:
    - DOCKER_REPO=
    - EB_REGION="us-east-2"
    - secure: travisEncryptedAWS_ACCOUNT_ID
    - secure: travisEncryptedAWS_ACCESS_KEY_ID
    - secure: travisEncryptedAWS_SECRET_ACCESS_KEY
    - secure: travisEncryptedDOCKER_USERNAME
    - secure: travisEncryptedDOCKER_PASSWORD

before_install:
  - pip install awscli
  - export PATH=$PATH:$HOME/.local/bin

script:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - chmod +x $TRAVIS_BUILD_DIR/install-jdk.sh
  - export JAVA_HOME=$HOME/openjdk17
  - $TRAVIS_BUILD_DIR/install-jdk.sh -F 17 --target $JAVA_HOME
  - chmod +x gradlew
  - ./gradlew assemble
  - cd server
  - sudo docker build -t tictactoe .

deploy:
  - provider: script
    script: bash dh_docker_push.sh
    on:
      branch: develop
  - provider: script
    script: bash aws_docker_push.sh
    on:
      branch: develop