/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs3321.examples.tictactoe.app;

import edu.isu.cs3321.examples.tictactoe.list.LinkedList;

import static edu.isu.cs3321.examples.tictactoe.utilities.StringUtils.join;
import static edu.isu.cs3321.examples.tictactoe.utilities.StringUtils.split;
import static edu.isu.cs3321.examples.tictactoe.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
