/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs3321.examples.tictactoe.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
